/*
 * Weiterbildungen für Architekt:innen BSc FH – Datenbestand
 *
 * Feldübersicht (pro Eintrag):
 *   id             eindeutiger Kurzname
 *   titel          offizieller Titel
 *   abschluss      MAS | DAS | CAS | Master | Fachausweis | Zertifikat | Lehrgang | Kurs | Register
 *   schule         Kurzname der Schule (für Filter)
 *   schuleVoll     ausgeschriebener Name / Kooperation
 *   themen         Liste aus THEMEN (siehe unten)
 *   ects           Zahl oder null
 *   dauerMonate    ungefähre Dauer in Monaten (für Filter), null = unbekannt
 *   dauerText      Dauer als Text
 *   kostenChf      Richtwert in CHF (für Filter/Sortierung), null = unbekannt
 *   kostenText     Kosten als Text
 *   zeitmodell     ["Teilzeit"] | ["Vollzeit"] | beides
 *   form           Präsenz | Blended | Online
 *   orte           Liste der Unterrichtsorte
 *   sprache        Liste der Unterrichtssprachen
 *   zulassungFh    ja | dossier | eingeschraenkt  (Zugang mit Bachelor FH Architektur)
 *   zulassung      Text
 *   start          nächster bekannter Start / Rhythmus
 *   inhalt         Was lernt man?
 *   relevanz       Warum relevant für Architekt:in BSc FH?
 *   nutzen         Wofür ist es brauchbar?
 *   passung        1–5, Passung zu den persönlichen Zielen
 *                  (Nachhaltigkeit, Umbau, KI, Selbständigkeit/Immobilien, Projektleitung)
 *   teilVon        ids übergeordneter Programme (stapelbar, z.B. CAS → MAS)
 *   url            Programmseite
 *   hinweis        Unsicherheiten / bitte prüfen
 *
 * Angaben ohne Gewähr. Massgebend ist immer die Programmseite der Schule.
 */
window.WEITERBILDUNGEN = {
  stand: "2026-10-03",
  profil: {
    titel: "Architekt BSc FH",
    ziele: ["Nachhaltigkeit", "Umbau & Bestand", "KI & Digitalisierung", "Eigenes Büro / Immobilien", "Projektleitung"]
  },
  themen: [
    "Nachhaltigkeit & Energie",
    "Umbau & Bestand",
    "Digitalisierung & KI",
    "Projektleitung",
    "Immobilien",
    "Unternehmertum",
    "Städtebau & Raum",
    "Holzbau",
    "Recht",
    "Entwurf & Theorie"
  ],
  programme: [
    // ───────────── Nachhaltigkeit & Energie ─────────────
    {
      id: "enbau-mas",
      titel: "MAS in nachhaltigem Bauen (EN Bau)",
      abschluss: "MAS",
      schule: "EN Bau",
      schuleVoll: "EN Bau – Kooperation mehrerer Fachhochschulen (u.a. FHNW, HSLU, BFH)",
      themen: ["Nachhaltigkeit & Energie", "Umbau & Bestand"],
      ects: 60,
      dauerMonate: 36,
      dauerText: "ca. 3 Jahre, modular (CAS einzeln belegbar)",
      kostenChf: 32000,
      kostenText: "CHF 30'000–34'000 je nach CAS-Wahl (CAS à CHF 6'400)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Olten", "Horw", "weitere je nach CAS"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss in Architektur, Bau oder verwandtem Gebiet und Berufserfahrung. Andere Profile sur dossier.",
      start: "Einstieg mit dem Grundmodul CAS Nachhaltiges Bauen (Herbst Olten, Frühling Horw)",
      inhalt: "Grundmodul CAS Nachhaltiges Bauen, danach vier Kompetenz-CAS nach Wahl (z.B. Zirkuläres Bauen, Baukultur, Energie in der Gebäudeerneuerung, Bauen mit Holz) und eine Master-Thesis.",
      relevanz: "Das Programm ist von mehreren Fachhochschulen gemeinsam getragen und genau auf Planende zugeschnitten. Es verbindet Ökologie, Energie, Kreislaufwirtschaft und Baukultur. Für Architekt:innen ist es die breiteste Spezialisierung in Richtung Netto-Null und Umbau.",
      nutzen: "Fachführung Nachhaltigkeit im Büro, Beratung von Bauherrschaften (SNBS, Minergie-ECO), Positionierung eines eigenen Büros mit klarem Nachhaltigkeitsprofil.",
      passung: 5,
      teilVon: [],
      url: "https://www.enbau.ch/nachhaltiges-bauen",
      hinweis: "Thesis-Gebühr CHF 4'000 wird bei Bestehen vom EN Bau übernommen."
    },
    {
      id: "enbau-cas-nb",
      titel: "CAS Nachhaltiges Bauen",
      abschluss: "CAS",
      schule: "FHNW",
      schuleVoll: "FHNW / HSLU im Rahmen von EN Bau",
      themen: ["Nachhaltigkeit & Energie"],
      ects: 10,
      dauerMonate: 4,
      dauerText: "4 Monate, 16 Kurstage (Do/Fr alle 2 Wochen) plus 3-tägige Einstiegsexkursion",
      kostenChf: 6400,
      kostenText: "CHF 6'400 (zzgl. ca. CHF 500 Exkursion)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Olten", "Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung oder Bau.",
      start: "Herbst in Olten (nächster Start 1.9.2027), Frühling in Horw",
      inhalt: "Grundlagen des nachhaltigen Bauens: graue Energie, Ökobilanz, Standards (SNBS, Minergie-ECO, SIA 2040), Suffizienz, gesundes Innenraumklima, Lebenszyklus.",
      relevanz: "Das CAS ist der kompakte Einstieg ins Thema und Pflichtgrundlage für den MAS. Danach kannst du Nachhaltigkeitsziele in eigenen Projekten fundiert begründen.",
      nutzen: "Nachhaltigkeitskonzepte in Wettbewerben und Vorprojekten, Argumentation gegenüber Bauherrschaften, Einstieg in den MAS EN Bau.",
      passung: 5,
      teilVon: ["enbau-mas"],
      url: "https://www.fhnw.ch/de/architektur-bau-geomatik/weiterbildung/angebot/weiterbildungen/cas-nachhaltiges-bauen",
      hinweis: ""
    },
    {
      id: "enbau-cas-zirk",
      titel: "CAS Zirkuläres Bauen",
      abschluss: "CAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern im Rahmen von EN Bau, mit ETH Zürich und SIA",
      themen: ["Nachhaltigkeit & Energie", "Umbau & Bestand"],
      ects: 10,
      dauerMonate: 4,
      dauerText: "4 Monate, 18 Kurstage (Do/Fr)",
      kostenChf: 6400,
      kostenText: "CHF 6'400 inkl. Unterlagen und Einschreibegebühr",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung oder Bau.",
      start: "jährlich im Frühling",
      inhalt: "Kreislaufdenken auf allen Massstäben: Synergien im Quartier, Umnutzung, Wiederverwendung von Bauteilen (Re-Use), kreislaufgerechtes Konstruieren, nachwachsende Baustoffe.",
      relevanz: "Re-Use und Weiterbauen sind die Kernthemen des Umbaus von morgen. Das CAS wird von Praktiker:innen der Re-Use-Szene geleitet und ist sehr nah an der Planungspraxis.",
      nutzen: "Bauteilkataloge und Re-Use-Konzepte in Projekten, Rückbaukonzepte, Positionierung als Spezialist:in für Kreislaufwirtschaft.",
      passung: 5,
      teilVon: ["enbau-mas"],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/bau/cas-zirkulaeres-bauen/",
      hinweis: "Wird auch von BFH und FHNW ausgeschrieben."
    },
    {
      id: "fhnw-cas-ege",
      titel: "CAS Energie in der Gebäudeerneuerung",
      abschluss: "CAS",
      schule: "FHNW",
      schuleVoll: "Fachhochschule Nordwestschweiz, Hochschule für Architektur, Bau und Geomatik",
      themen: ["Nachhaltigkeit & Energie", "Umbau & Bestand"],
      ects: 10,
      dauerMonate: 3,
      dauerText: "3 Monate, 16 Kurstage inkl. 4-tägiger Einstiegswoche",
      kostenChf: 6400,
      kostenText: "CHF 6'400 (zzgl. ca. CHF 400 Lehrmittel, Exkursionen)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Olten"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation und Berufserfahrung im Bau.",
      start: "jährlich im September",
      inhalt: "Energetische Analyse bestehender Gebäude, Gebäudehülle, Bauphysik im Bestand, Haustechnik-Ersatz, Erneuerungsstrategien und Fördermittel.",
      relevanz: "Der Gebäudepark der Schweiz wird vor allem erneuert, nicht neu gebaut. Das CAS liefert das technische Rüstzeug, um Sanierungen energetisch richtig zu planen.",
      nutzen: "Sanierungsprojekte, Erneuerungsstrategien für Portfolios, GEAK-nahe Beratung, Grundlage für ein eigenes Umbau-Büro.",
      passung: 5,
      teilVon: ["enbau-mas", "fhnw-mas-nee"],
      url: "https://www.fhnw.ch/de/weiterbildung/architektur-bau-geomatik/energie-am-bau/cas-energie-in-der-gebaeudeerneuerung",
      hinweis: ""
    },
    {
      id: "fhnw-cas-eab",
      titel: "CAS Energie am Bau",
      abschluss: "CAS",
      schule: "FHNW",
      schuleVoll: "Fachhochschule Nordwestschweiz, Hochschule für Architektur, Bau und Geomatik",
      themen: ["Nachhaltigkeit & Energie"],
      ects: 10,
      dauerMonate: 3,
      dauerText: "3 Monate, 16 Kurstage",
      kostenChf: 6400,
      kostenText: "CHF 6'400",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Olten"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation und Berufserfahrung im Bau.",
      start: "jährlich",
      inhalt: "Energieeffizientes Bauen: Bauphysik, Gebäudetechnik, erneuerbare Energien, Minergie, Energienachweise und Systemdenken.",
      relevanz: "Das CAS schliesst Lücken aus dem Bachelor bei Gebäudetechnik und Energie, damit du mit Fachplanern auf Augenhöhe diskutieren kannst.",
      nutzen: "Energiekonzepte in frühen Projektphasen, Koordination mit HLKS-Planern, Grundlage für weitere Energie-CAS.",
      passung: 4,
      teilVon: ["fhnw-mas-nee", "enbau-mas"],
      url: "https://www.fhnw.ch/de/weiterbildung/architektur-bau-geomatik/energie-am-bau/cas-energie-am-bau",
      hinweis: ""
    },
    {
      id: "fhnw-mas-nee",
      titel: "MAS Nachhaltigkeit und Energie am Bau",
      abschluss: "MAS",
      schule: "FHNW",
      schuleVoll: "Fachhochschule Nordwestschweiz, Hochschule für Architektur, Bau und Geomatik",
      themen: ["Nachhaltigkeit & Energie", "Umbau & Bestand", "Projektleitung"],
      ects: 60,
      dauerMonate: 36,
      dauerText: "ca. 3 Jahre, 5 CAS plus Master-Thesis",
      kostenChf: 36000,
      kostenText: "CHF 36'000",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Olten"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation und Berufserfahrung im Bau.",
      start: "Einstieg über ein CAS laufend möglich",
      inhalt: "Pflicht-CAS Energie und Ökologie am Bau, Management Skills (Projektmanagement, Kommunikation, Führung) und Energetische Gebäudeerneuerung, dazu zwei Wahl-CAS und eine Master-Thesis.",
      relevanz: "Der MAS kombiniert Energie-Fachwissen mit Management-Skills. Das passt gut, wenn du Nachhaltigkeit und Projektleitung zusammenbringen willst.",
      nutzen: "Leitung von Erneuerungsprojekten, Fachstelle Nachhaltigkeit in Büro oder Verwaltung, Energieberatung.",
      passung: 5,
      teilVon: [],
      url: "https://www.fhnw.ch/de/architektur-bau-geomatik/weiterbildung/angebot/weiterbildungen/mas-nachhaltigkeit-und-energie-am-bau",
      hinweis: ""
    },
    {
      id: "hslu-cas-baukultur",
      titel: "CAS Baukultur",
      abschluss: "CAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern, Institut für Architektur (EN Bau)",
      themen: ["Umbau & Bestand", "Entwurf & Theorie", "Nachhaltigkeit & Energie"],
      ects: 10,
      dauerMonate: 4,
      dauerText: "4 Monate, 16 Unterrichtstage (Freitag)",
      kostenChf: 6400,
      kostenText: "CHF 6'400",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung oder Bau.",
      start: "26.2.2027 (Anmeldeschluss 8.1.2027)",
      inhalt: "Hohe Baukultur nach Davos-Qualitätssystem: Ort, Kontext, Gestaltung, Funktionalität, Umgang mit dem Bestand; Instrumente zur Beurteilung von Qualität.",
      relevanz: "Das CAS gibt dir Sprache und Kriterien, um gestalterische Qualität und Weiterbauen im Bestand zu begründen, auch gegenüber Behörden und Jurys.",
      nutzen: "Wettbewerbe und Jurytätigkeit, Gestaltungsbeiräte, Argumentation bei Umbauten im sensiblen Kontext.",
      passung: 4,
      teilVon: ["enbau-mas"],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/bau/cas-baukultur/",
      hinweis: ""
    },
    {
      id: "zhaw-cas-nek",
      titel: "CAS Nachhaltiges Entwerfen und Konstruieren",
      abschluss: "CAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Nachhaltigkeit & Energie", "Entwurf & Theorie"],
      ects: 12,
      dauerMonate: 7,
      dauerText: "7 Monate, 19 Tage (2 Tage pro Monat) plus ca. 200 h Selbststudium",
      kostenChf: 6400,
      kostenText: "CHF 6'400 inkl. Unterlagen und Exkursion",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss in Architektur oder verwandtem Gebiet und Berufspraxis.",
      start: "4.9.2026",
      inhalt: "Nachhaltigkeit als Entwurfsthema: Materialwahl, Konstruktion, Lowtech, Tragwerk und graue Energie direkt am Entwurf geübt.",
      relevanz: "Das CAS ist eher entwurfs- als technikorientiert. Nachhaltigkeit wird zur gestalterischen Strategie, das liegt nah am Selbstverständnis von Architekt:innen.",
      nutzen: "Wettbewerbe, Konstruktionsentscheide in frühen Phasen, Profilierung als entwerfende:r Architekt:in mit Nachhaltigkeitsfokus.",
      passung: 5,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/weiterbildung/detail/kurs/cas-nachhaltiges-entwerfen-und-konstruieren",
      hinweis: ""
    },
    {
      id: "hslu-mas-eig",
      titel: "MAS Energieingenieur:in Gebäude",
      abschluss: "MAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Technik & Architektur, unterstützt von EnergieSchweiz",
      themen: ["Nachhaltigkeit & Energie"],
      ects: 60,
      dauerMonate: 22,
      dauerText: "ca. 22 Monate, 2 Tage/Woche Hochschule, 3 Tage Praxis",
      kostenChf: 16000,
      kostenText: "CHF 16'000 (vergünstigt dank EnergieSchweiz)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "dossier",
      zulassung: "Hochschulabschluss in Technik oder Architektur; Quereinstieg mit Passerelle. Praxisstelle in der Energiebranche wird erwartet.",
      start: "jährlich",
      inhalt: "Gebäudetechnik, Energiesysteme, Simulation, Bauphysik und Betriebsoptimierung, um vom Architektur- oder Ingenieurberuf in die Energieplanung zu wechseln.",
      relevanz: "Das ist ein Umstieg mehr als eine Ergänzung: Du wirst zur Energiefachperson. Interessant, wenn dich die Technik hinter Netto-Null mehr reizt als der Entwurf.",
      nutzen: "Energieplanung, Gesamtenergiekonzepte, Fachplanung Gebäudetechnik, Schnittstelle Architektur/HLKS.",
      passung: 3,
      teilVon: [],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/studienprogramm/mas/",
      hinweis: "Programm-Details (u.a. Passerelle) direkt bei der HSLU prüfen."
    },
    {
      id: "hesso-mas-eddbat",
      titel: "MAS HES-SO en Énergie et développement durable dans l'environnement bâti (EDD-BAT)",
      abschluss: "MAS",
      schule: "HES-SO",
      schuleVoll: "HES-SO: HEIA-FR, HEPIA, HES-SO Valais, HEIG-VD",
      themen: ["Nachhaltigkeit & Energie", "Umbau & Bestand"],
      ects: 60,
      dauerMonate: 36,
      dauerText: "3 Jahre, jeweils freitags",
      kostenChf: 22900,
      kostenText: "CHF 22'900",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Fribourg", "Genf", "Sion", "Yverdon-les-Bains"],
      sprache: ["Französisch"],
      zulassungFh: "ja",
      zulassung: "Architekt:innen oder Ingenieur:innen EPF/UNI/HES; andere Profile sur dossier.",
      start: "periodisch",
      inhalt: "Energie und nachhaltige Entwicklung im Gebäudebereich: Bauphysik, Energiesysteme, Renovation, Ökobilanz, Planungsprozesse.",
      relevanz: "Das Westschweizer Pendant zum EN-Bau-MAS. Es ist günstiger und baut dein Französisch und dein Netzwerk in der Romandie auf.",
      nutzen: "Nachhaltigkeitsprojekte in der Romandie, zweisprachiges Profil, Netzwerk in der Westschweiz.",
      passung: 3,
      teilVon: [],
      url: "https://heig-vd.ch/formation/formation-continue/mas-hes-so-en-energie-et-developpement-durable-dans-lenvironnement-bati-edd-bat",
      hinweis: ""
    },
    {
      id: "sanu-baubio",
      titel: "Baubiologe/Baubiologin mit eidg. Fachausweis",
      abschluss: "Fachausweis",
      schule: "sanu",
      schuleVoll: "sanu future learning ag (Vorbereitung auf die eidg. Berufsprüfung)",
      themen: ["Nachhaltigkeit & Energie"],
      ects: null,
      dauerMonate: 14,
      dauerText: "29 Kurstage verteilt auf 12–15 Monate, Module einzeln belegbar",
      kostenChf: 16800,
      kostenText: "CHF 16'800; nach der Berufsprüfung 50 % Bundesbeitrag",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich", "Bern"],
      sprache: ["Deutsch"],
      zulassungFh: "dossier",
      zulassung: "Für die Prüfung: EFZ in einem Bauberuf mit 2 Jahren Praxis oder gleichwertige Qualifikation; FH-Abschluss wird in der Regel als gleichwertig anerkannt (prüfen).",
      start: "August 2026",
      inhalt: "Gesundes Bauen: Schadstoffe, Raumklima, Materialien, Elektrosmog, Feuchte, Akustik, Licht, baubiologische Beratung und Messung.",
      relevanz: "Eine praxisnahe Ergänzung zu Nachhaltigkeit: Gesundheit und Materialökologie. Kunden fragen zunehmend danach, und im Umbau stösst du oft auf Schadstoffe.",
      nutzen: "Baubiologische Beratung, Materialkonzepte, Schadstoffabklärung im Umbau, Nischenprofil für ein eigenes Büro.",
      passung: 3,
      teilVon: [],
      url: "https://www.sanu.ch/lehrgaenge/gesundes-und-nachhaltiges-bauen",
      hinweis: "Kein Hochschulabschluss, sondern eidg. Berufsprüfung."
    },

    // ───────────── Umbau & Bestand ─────────────
    {
      id: "bfh-mas-denkmal",
      titel: "MAS Denkmalpflege und Umnutzung",
      abschluss: "MAS",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule, Architektur, Holz und Bau",
      themen: ["Umbau & Bestand", "Entwurf & Theorie"],
      ects: 60,
      dauerMonate: 24,
      dauerText: "mind. 2 Jahre; 16 Module à 3 ECTS plus Master-Thesis",
      kostenChf: 23600,
      kostenText: "CHF 23'600 total (Einzelmodul CHF 1'350)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Burgdorf"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss in Architektur, Bau, Kunstgeschichte o.ä. und Berufspraxis; sur dossier möglich.",
      start: "laufender Einstieg, alle fünf Wochen beginnt ein neues Modul (Freitag)",
      inhalt: "Denkmalpflegetheorie, Bauforschung, Inventarisation, Materialkunde historischer Bauten, Umnutzungsstrategien, Bauten des 20. Jahrhunderts, Recht und Praxis der Denkmalpflege.",
      relevanz: "Der Schweizer Klassiker für den Umgang mit Bestand. Wer Umbau als Kernkompetenz will, lernt hier, Altbauten zu lesen und sorgfältig weiterzubauen.",
      nutzen: "Umbau- und Umnutzungsprojekte, Arbeit mit Denkmalpflege, Stellen in Fachstellen, Profil für ein Umbau-Büro.",
      passung: 5,
      teilVon: [],
      url: "https://www.bfh.ch/de/weiterbildung/mas/denkmalpflege-umnutzung/",
      hinweis: "Einzelne Module lassen sich auch als Kurse ohne MAS besuchen."
    },
    {
      id: "zhaw-cas-bestand",
      titel: "CAS Weiterbauen im Bestand",
      abschluss: "CAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Umbau & Bestand", "Nachhaltigkeit & Energie"],
      ects: 12,
      dauerMonate: 6,
      dauerText: "6 Monate, 18 Tage (2 Tage pro Monat)",
      kostenChf: 6900,
      kostenText: "CHF 6'900 inkl. Unterlagen und Exkursionen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Offen für Architekt:innen und Handwerker:innen mit Berufserfahrung. 17–24 Teilnehmende.",
      start: "11.9.2026",
      inhalt: "Analyse und Bewertung bestehender Bauten, Konstruktion im Bestand, handwerkliche Techniken, Umbaustrategien; eingebettet in ein Interreg-Forschungsprojekt.",
      relevanz: "Kompakt, praxisnah und mit Handwerk verzahnt. Das ist ideal, um Umbau als Schwerpunkt aufzubauen, ohne gleich einen MAS anzugehen.",
      nutzen: "Umbauprojekte vom Bestandsaufnahme bis Detail, Zusammenarbeit mit Handwerk, Akquisition von Umbauaufträgen.",
      passung: 5,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/weiterbildung/detail/kurs/cas-weiterbauen-im-bestand",
      hinweis: ""
    },
    {
      id: "eth-cas-arc-bestand",
      titel: "CAS ETH ARC in Bestand",
      abschluss: "CAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Departement Architektur – Kompetenzzentrum ARC",
      themen: ["Umbau & Bestand", "Immobilien", "Projektleitung"],
      ects: 12,
      dauerMonate: 12,
      dauerText: "2 Semester, Freitagnachmittag und Samstagvormittag",
      kostenChf: 14000,
      kostenText: "CHF 14'000 inkl. Unterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Master oder gleichwertiges Diplom in Architektur/Bau und mind. 2 Jahre Berufserfahrung. Mit FH-Bachelor nur sur dossier nachfragen.",
      start: "jährlich im Herbst",
      inhalt: "Strategien im Umgang mit dem Gebäudebestand aus Sicht von Eigentümern, Planenden und Investoren: Bestandsanalyse, Werterhalt, Erneuerungsstrategien, Wirtschaftlichkeit.",
      relevanz: "Das CAS betrachtet den Umbau aus der strategischen Bauherren- und Immobiliensicht. Das ist wertvoll, wenn du später Bestandsportfolios entwickeln oder beraten willst.",
      nutzen: "Erneuerungsstrategien für Portfolios, Beratung von Eigentümern, Schnittstelle Architektur/Immobilienwirtschaft.",
      passung: 4,
      teilVon: [],
      url: "https://kompetenz.arch.ethz.ch/kurs/cas-eth-arc-bestand/",
      hinweis: "Kosten, Dauer und Zulassung analog zu den übrigen CAS ETH ARC angenommen. Bitte auf der Programmseite prüfen."
    },

    // ───────────── Digitalisierung & KI ─────────────
    {
      id: "fhnw-mas-db",
      titel: "MAS Digitales Bauen",
      abschluss: "MAS",
      schule: "FHNW",
      schuleVoll: "FHNW, Institut Digitales Bauen",
      themen: ["Digitalisierung & KI", "Projektleitung"],
      ects: 60,
      dauerMonate: 30,
      dauerText: "ca. 2–3 Jahre, CAS in flexibler Reihenfolge",
      kostenChf: 32000,
      kostenText: "CHF 32'000 (zzgl. Innovationsreisen Norwegen und Stanford)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Muttenz"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in der Bau- oder Immobilienbranche.",
      start: "Einstieg über ein CAS",
      inhalt: "BIM, Virtual Design and Construction (VDC-Zertifikat von Stanford als Pflichtteil), integrierte Projektabwicklung, digitale Transformation von Organisationen.",
      relevanz: "Der MAS bringt Digitalisierung und Projektleitung zusammen. Du lernst, wie datenbasierte Projektabwicklung funktioniert. Das ist die Grundlage, um später auch KI-Werkzeuge sinnvoll einzusetzen.",
      nutzen: "BIM-Gesamtleitung, digitale Projektabwicklung, Transformation im eigenen Büro, Rollen wie BIM-Manager:in.",
      passung: 4,
      teilVon: [],
      url: "https://www.fhnw.ch/de/weiterbildung/architektur-bau-geomatik/digitales-bauen/mas-fhnw-digitales-bauen",
      hinweis: "Unterrichtsort bitte prüfen (Institut in Muttenz)."
    },
    {
      id: "fhnw-cas-db-ipm",
      titel: "CAS Digitales Bauen – Integriertes Projektmanagement",
      abschluss: "CAS",
      schule: "FHNW",
      schuleVoll: "FHNW, Institut Digitales Bauen",
      themen: ["Digitalisierung & KI", "Projektleitung"],
      ects: 15,
      dauerMonate: 10,
      dauerText: "10 Monate",
      kostenChf: 9600,
      kostenText: "CHF 9'600",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Muttenz"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in der Bau- oder Immobilienbranche.",
      start: "jährlich",
      inhalt: "BIM-Methode in der Planungsphase, digitale Bauwerksmodelle auf der Baustelle, integrierte Projektabwicklung (IPA), Lean Construction.",
      relevanz: "Dieses CAS ist der projektnahe Teil des MAS: Du lernst, Projekte digital und kollaborativ zu führen. Das verbindet deine Ziele Projektleitung und Digitalisierung direkt.",
      nutzen: "BIM-Projektleitung, Einführung von IPA/Lean im Projekt, Koordination digitaler Planungsteams.",
      passung: 4,
      teilVon: ["fhnw-mas-db"],
      url: "https://www.fhnw.ch/de/weiterbildung/architektur-bau-geomatik/digitales-bauen/cas-db-integriertes-projektmanagement",
      hinweis: ""
    },
    {
      id: "fhnw-cas-db-tw",
      titel: "CAS Digitales Bauen – Transformation & Wertschöpfung in Organisationen",
      abschluss: "CAS",
      schule: "FHNW",
      schuleVoll: "FHNW, Institut Digitales Bauen",
      themen: ["Digitalisierung & KI", "Unternehmertum"],
      ects: 15,
      dauerMonate: 10,
      dauerText: "10 Monate",
      kostenChf: 9600,
      kostenText: "CHF 9'600",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Muttenz"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in der Bau- oder Immobilienbranche.",
      start: "jährlich",
      inhalt: "Digitale Geschäftsmodelle, Prozessdesign, Change Management und Wertschöpfung durch Daten in Planungs- und Bauunternehmen.",
      relevanz: "Das CAS richtet sich an alle, die ein Büro digital neu aufstellen wollen. Es passt zum Ziel eines eigenen, schlanken und digitalen Büros.",
      nutzen: "Digitalstrategie für ein eigenes oder bestehendes Büro, neue Dienstleistungen, Prozessoptimierung.",
      passung: 4,
      teilVon: ["fhnw-mas-db"],
      url: "https://www.fhnw.ch/de/weiterbildung/architektur-bau-geomatik/digitales-bauen/cas-db-transformation-wertschoepfung",
      hinweis: ""
    },
    {
      id: "eth-cas-arc-dig",
      titel: "CAS ETH ARC in Digitalisierung",
      abschluss: "CAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Departement Architektur – Kompetenzzentrum ARC",
      themen: ["Digitalisierung & KI", "Immobilien"],
      ects: 12,
      dauerMonate: 12,
      dauerText: "2 Semester, Freitagnachmittag und Samstagvormittag",
      kostenChf: 14000,
      kostenText: "CHF 14'000 inkl. Unterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Master oder gleichwertiges Diplom und mind. 2 Jahre Berufserfahrung. Mit FH-Bachelor sur dossier nachfragen.",
      start: "jährlich im Herbst",
      inhalt: "Digitales Umfeld von Bauwirtschaft und Immobilienmarkt: Daten, Plattformen, digitale Geschäftsmodelle, Automatisierung, praxisnah an Projekten.",
      relevanz: "Das CAS zeigt die strategische Seite der Digitalisierung und nicht nur Werkzeuge. Es passt, wenn du verstehen willst, wie Daten und KI das Geschäft von Planenden verändern.",
      nutzen: "Digitalstrategie, neue Geschäftsfelder, Gespräche mit Investoren und PropTech-Firmen.",
      passung: 4,
      teilVon: [],
      url: "https://kompetenz.arch.ethz.ch/kurs/cas-eth-arc-digitalisierung/",
      hinweis: "Kosten und ECTS analog zu den übrigen CAS ETH ARC. Bitte prüfen."
    },
    {
      id: "fhnw-ki-modul",
      titel: "Modul Künstliche Intelligenz (Architektur, Bau und Geomatik)",
      abschluss: "Kurs",
      schule: "FHNW",
      schuleVoll: "FHNW, Hochschule für Architektur, Bau und Geomatik",
      themen: ["Digitalisierung & KI"],
      ects: null,
      dauerMonate: 1,
      dauerText: "2 × 2 Tage",
      kostenChf: 2100,
      kostenText: "CHF 2'100",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Olten"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Fachleute aus Architektur, Bau und Geomatik.",
      start: "1.10.2026",
      inhalt: "Moderne KI-Methoden anwenden, Data-Science-Projekte aufsetzen, räumliche Analysen mit KI, Chancen und Grenzen in der Baubranche.",
      relevanz: "Der günstigste und schnellste Einstieg in KI mit Bezug zur Baubranche. So kannst du testen, ob du tiefer einsteigen willst.",
      nutzen: "Erste KI-Anwendungen im Büro (Analysen, Automatisierung), fundierte Einschätzung von KI-Tools.",
      passung: 4,
      teilVon: [],
      url: "https://www.fhnw.ch/de/architektur-bau-geomatik/weiterbildung/angebot/weiterbildungen/modul-kunstliche-intelligenz",
      hinweis: ""
    },
    {
      id: "bfh-cas-ki",
      titel: "CAS Künstliche Intelligenz – Grundlagen und Anwendung",
      abschluss: "CAS",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule, Technik und Informatik",
      themen: ["Digitalisierung & KI"],
      ects: 12,
      dauerMonate: 6,
      dauerText: "Okt.–Apr. (KW 43–14), jeweils mittwochs",
      kostenChf: 7850,
      kostenText: "CHF 7'850",
      zeitmodell: ["Teilzeit"],
      form: "Blended",
      orte: ["Biel", "Online"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation; keine Programmierkenntnisse auf Expertenniveau nötig.",
      start: "21.10.2026",
      inhalt: "Grundlagen von Machine Learning und generativer KI, Anwendungsfälle, Datenqualität, Ethik und Recht, eigene KI-Projekte konzipieren.",
      relevanz: "Das CAS ist branchenneutral, aber fundiert. Danach verstehst du KI gut genug, um sie im Büro gezielt einzusetzen, statt nur Tools auszuprobieren.",
      nutzen: "KI-Strategie fürs Büro, Automatisierung von Routinearbeiten, Rolle als KI-Verantwortliche:r.",
      passung: 4,
      teilVon: [],
      url: "https://www.bfh.ch/de/weiterbildung/cas/kuenstliche-intelligenz-grundlagen-und-anwendung/",
      hinweis: "Unterlagen teilweise auf Englisch."
    },
    {
      id: "ffhs-cas-genki",
      titel: "CAS Generative Künstliche Intelligenz",
      abschluss: "CAS",
      schule: "FFHS",
      schuleVoll: "Fernfachhochschule Schweiz",
      themen: ["Digitalisierung & KI"],
      ects: 10,
      dauerMonate: 6,
      dauerText: "1 Semester",
      kostenChf: 5900,
      kostenText: "CHF 5'700 plus CHF 200 Einschreibegebühr",
      zeitmodell: ["Teilzeit"],
      form: "Blended",
      orte: ["Zürich", "Bern", "Online"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation; keine vertieften IT-Kenntnisse nötig.",
      start: "August und Februar",
      inhalt: "Generative KI (Text, Bild, Code) kompetent nutzen, kritisch beurteilen und in Organisationen einführen; 80 % begleitetes Selbststudium, 20 % Präsenz.",
      relevanz: "Sehr gut mit Vollzeitarbeit vereinbar. Bildgeneratoren und Sprachmodelle verändern Visualisierung, Wettbewerbe und Administration im Büro direkt.",
      nutzen: "KI-gestützte Visualisierung und Ideenfindung, Texte und Berichte, KI-Einführung im Team.",
      passung: 4,
      teilVon: [],
      url: "https://www.ffhs.ch/en/degree-programmes/continuing-education/cas-generative-kuenstliche-intelligenz",
      hinweis: ""
    },
    {
      id: "epfl-ads-ml",
      titel: "Applied Data Science: Machine Learning",
      abschluss: "Zertifikat",
      schule: "EPFL",
      schuleVoll: "EPFL Extension School (Certificate of Open Studies)",
      themen: ["Digitalisierung & KI"],
      ects: 15,
      dauerMonate: 10,
      dauerText: "ca. 420 Lernstunden, Tempo frei wählbar",
      kostenChf: 4900,
      kostenText: "CHF 490 pro Monat (bei ca. 10 Monaten ≈ CHF 4'900)",
      zeitmodell: ["Teilzeit"],
      form: "Online",
      orte: ["Online"],
      sprache: ["Englisch"],
      zulassungFh: "ja",
      zulassung: "Offen; Grundkenntnisse in Mathematik und Programmierung (Python) empfohlen.",
      start: "jederzeit",
      inhalt: "Python, Datenanalyse, Machine Learning, neuronale Netze und Deep Learning mit einem eigenen Abschlussprojekt.",
      relevanz: "Das ist die technischste Option: Du lernst, KI selbst zu bauen und nicht nur anzuwenden. Interessant, wenn du z.B. eigene Tools für Planung oder Immobilienanalysen entwickeln willst.",
      nutzen: "Eigene Datenanalysen (z.B. Standort, Flächen, Energie), Prototypen für PropTech-Ideen, computational design.",
      passung: 3,
      teilVon: [],
      url: "https://www.epfl.ch/education/continuing-education/applied-data-science-machine-learning/",
      hinweis: "Angebot und Preis bitte prüfen, die EPFL Extension School wurde umstrukturiert."
    },
    {
      id: "eth-mas-dfab",
      titel: "MAS ETH in Architecture and Digital Fabrication",
      abschluss: "MAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Gramazio Kohler Research / NCCR Digital Fabrication",
      themen: ["Digitalisierung & KI", "Entwurf & Theorie", "Holzbau"],
      ects: 60,
      dauerMonate: 12,
      dauerText: "1 Jahr Vollzeit",
      kostenChf: 21460,
      kostenText: "CHF 21'460 (Stipendien CHF 5'000–20'000 möglich)",
      zeitmodell: ["Vollzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Englisch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "In der Regel Master in Architektur oder verwandtem Gebiet; Portfolio. Sehr kompetitiv.",
      start: "jährlich im September",
      inhalt: "Computational Design, Robotik, digitale Fertigung im Massstab 1:1, Forschung an realen Prototypen.",
      relevanz: "International sichtbares Spitzenprogramm, aber Vollzeit und forschungsorientiert. Es lohnt sich, wenn du in Richtung Computational Design oder Forschung willst.",
      nutzen: "Computational Design, Forschung, Spezialrollen in Büros mit digitaler Fertigung, Holzbau-Industrie.",
      passung: 2,
      teilVon: [],
      url: "https://sce.ethz.ch/en/programmes-and-courses/search-current-courses/mas/mas-eth-dfab.html",
      hinweis: ""
    },

    // ───────────── Projektleitung ─────────────
    {
      id: "hslu-mas-bm",
      titel: "MAS Baumanagement",
      abschluss: "MAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Technik & Architektur",
      themen: ["Projektleitung", "Recht"],
      ects: 60,
      dauerMonate: 40,
      dauerText: "ca. 40 Monate; DAS Baumanagement als Basis, dann 2 Vertiefungs-CAS",
      kostenChf: 35700,
      kostenText: "ab CHF 35'700 inkl. Master-Thesis (CHF 4'500)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Tertiärer Abschluss (FH/Uni/HF) und Berufserfahrung im Bau; sur dossier möglich.",
      start: "Einstieg über die CAS des DAS Baumanagement",
      inhalt: "Projektmanagement Bau, Kommunikation und Führung, dazu Wahl-CAS aus Betriebswirtschaft Bau, Strategisches Projektmanagement Bau, Baukostenplanung oder Baurecht.",
      relevanz: "Das ist der umfassendste Weg zur Gesamtprojektleitung. Kosten, Recht, Führung und Betriebswirtschaft decken genau die Themen ab, die im Bachelor zu kurz kommen.",
      nutzen: "Gesamtprojektleitung, Bauherrenvertretung, Führung eines Büros oder Teams.",
      passung: 5,
      teilVon: [],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/bau/mas-baumanagement/",
      hinweis: "Auch als DAS Baumanagement (zwei CAS) abschliessbar."
    },
    {
      id: "hslu-cas-pmb",
      titel: "CAS Projektmanagement Bau",
      abschluss: "CAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Technik & Architektur",
      themen: ["Projektleitung"],
      ects: 18,
      dauerMonate: 11,
      dauerText: "11 Monate",
      kostenChf: 11500,
      kostenText: "CHF 11'500",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Tertiärer Abschluss und Berufserfahrung im Bau.",
      start: "5.4.2027 (Variante KBOB: 31.8.2026)",
      inhalt: "Projektorganisation, Termine, Kosten, Qualität, Risiko, Vertragswesen und Verhandlungsführung über alle SIA-Phasen.",
      relevanz: "Das CAS ist der direkte Schritt von der Planung zur Projektleitung und gleichzeitig der Pflichtteil des MAS Baumanagement.",
      nutzen: "Projektleitung im Planungsbüro oder bei Bauherrschaften, Grundlage für Gesamtleitung.",
      passung: 5,
      teilVon: ["hslu-mas-bm"],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/bau/cas-projektmanagement-bau/",
      hinweis: "Es gibt eine Variante «KBOB» mit Fokus auf öffentliche Bauherren."
    },
    {
      id: "hslu-cas-kfb",
      titel: "CAS Kommunikation und Führung Bau",
      abschluss: "CAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Technik & Architektur",
      themen: ["Projektleitung", "Unternehmertum"],
      ects: null,
      dauerMonate: 8,
      dauerText: "8 Monate",
      kostenChf: 6900,
      kostenText: "CHF 6'900 inkl. Einschreibegebühr",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Tertiärer Abschluss und Berufserfahrung im Bau.",
      start: "Mai (zuletzt 5.5.2026)",
      inhalt: "Führung von Teams und Projekten, Kommunikation mit Bauherrschaft und Behörden, Konfliktmanagement, Selbstmanagement.",
      relevanz: "Die Soft Skills machen den Unterschied zwischen guter Planerin und guter Projektleiterin. Für ein eigenes Büro zahlt sich das besonders aus.",
      nutzen: "Team- und Projektführung, schwierige Gespräche mit Bauherrschaft, Moderation von Sitzungen.",
      passung: 4,
      teilVon: ["hslu-mas-bm"],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/bau/cas-kommunikation-und-fuehrung-bau/",
      hinweis: "ECTS nicht verifiziert."
    },
    {
      id: "hslu-cas-spmb",
      titel: "CAS Strategisches Projektmanagement Bau",
      abschluss: "CAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Technik & Architektur",
      themen: ["Projektleitung", "Immobilien"],
      ects: 10,
      dauerMonate: 6,
      dauerText: "6 Monate",
      kostenChf: 6400,
      kostenText: "CHF 6'400",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Tertiärer Abschluss und Berufserfahrung im Bau.",
      start: "19.1.2027",
      inhalt: "Projektdefinition, Bedarfsplanung, Beschaffungsmodelle, Portfoliosicht und strategische Steuerung aus Bauherrensicht.",
      relevanz: "Das CAS deckt die frühen, strategischen Phasen ab, in denen Projekte entschieden werden. Das braucht es auch für eigene Immobilienprojekte.",
      nutzen: "Bauherrenberatung, Machbarkeitsstudien, Wahl von Beschaffungsmodellen.",
      passung: 4,
      teilVon: ["hslu-mas-bm"],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/bau/cas-strategisches-projektmanagement-bau/",
      hinweis: ""
    },
    {
      id: "zhaw-cas-besteller",
      titel: "CAS Bestellerkompetenz – Projekt- und Gesamtleitung im Bauprozess",
      abschluss: "CAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Projektleitung", "Immobilien"],
      ects: 10,
      dauerMonate: 9,
      dauerText: "9 Monate, jeden 2. Freitag plus 3 externe Seminare",
      kostenChf: 8900,
      kostenText: "CHF 8'900 inkl. Kursunterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung, Bau oder Immobilien.",
      start: "25.9.2026 bis 2.7.2027",
      inhalt: "Die Rolle der Bestellerin: Projektdefinition, Organisation, Verträge, Kosten- und Terminsteuerung, Gesamtleitung und Bauherrenvertretung.",
      relevanz: "Das CAS trainiert den Seitenwechsel zur Bauherrschaft. Es eignet sich, wenn du Gesamtleitungen übernehmen oder später eigene Projekte als Bauherr:in steuern willst.",
      nutzen: "Bauherrenvertretung, Gesamtleitung, Stellen bei öffentlichen oder institutionellen Bauherren.",
      passung: 5,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/weiterbildung/detail/kurs/cas-bestellerkompetenz-projekt-und-gesamtleitung-im-bauprozess",
      hinweis: ""
    },
    {
      id: "zhaw-cas-baumgmt",
      titel: "CAS Baumanagement S, M, L, XL",
      abschluss: "CAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Projektleitung"],
      ects: null,
      dauerMonate: 6,
      dauerText: "ca. 1 Semester",
      kostenChf: 6900,
      kostenText: "CHF 6'900",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung oder Bau.",
      start: "jährlich",
      inhalt: "Baumanagement für Projekte jeder Grösse: Ausschreibung, Kostenplanung, Bauleitung, Termin- und Qualitätsmanagement.",
      relevanz: "Das CAS deckt die Ausführungsseite ab (Ausschreibung bis Abnahme). Gerade für ein kleines eigenes Büro ist dieses Wissen Gold wert.",
      nutzen: "Ausführungsplanung und Bauleitung im eigenen Büro, Kostensicherheit bei Umbauten.",
      passung: 4,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/weiterbildung/detail/kurs/cas-baumanagement",
      hinweis: "ECTS und Dauer nicht verifiziert."
    },
    {
      id: "eth-cas-arc-gpl",
      titel: "CAS ETH ARC in Gesamtprojektleitung",
      abschluss: "CAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Departement Architektur – Kompetenzzentrum ARC",
      themen: ["Projektleitung", "Immobilien"],
      ects: 12,
      dauerMonate: 12,
      dauerText: "2 Semester, Fr 13–19 Uhr und Sa 9–13 Uhr",
      kostenChf: 14000,
      kostenText: "CHF 14'000 inkl. Unterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Master oder gleichwertiges Diplom in Architektur/Bau/Umwelt und mind. 2 Jahre Berufserfahrung. Mit FH-Bachelor sur dossier nachfragen.",
      start: "jährlich im Herbst",
      inhalt: "Projektmanagement über den ganzen Planungs- und Bauprozess in Bau, Architektur und Immobilien; ca. 12 Teilnehmende.",
      relevanz: "Kleine Klasse und ein starkes ETH-Netzwerk. Inhaltlich ähnlich wie FH-Angebote, aber teurer und mit höherer Zulassungshürde.",
      nutzen: "Gesamtprojektleitung, Netzwerk zu Bauherren und Investoren.",
      passung: 4,
      teilVon: [],
      url: "https://kompetenz.arch.ethz.ch/kurs/cas-eth-arc-gesamtprojektleitung/",
      hinweis: ""
    },
    {
      id: "ipma-c",
      titel: "IPMA Level C – Zertifizierte:r Projektmanager:in",
      abschluss: "Zertifikat",
      schule: "VZPM / diverse",
      schuleVoll: "Zertifizierung durch VZPM; Vorbereitung z.B. ZHAW, 4Projects, thebit",
      themen: ["Projektleitung"],
      ects: null,
      dauerMonate: 4,
      dauerText: "Vorbereitung 6–8 Tage, Zertifizierung über einige Monate",
      kostenChf: 7000,
      kostenText: "Zertifizierung CHF 3'200 plus Vorbereitungskurs ca. CHF 3'600–6'700",
      zeitmodell: ["Teilzeit"],
      form: "Blended",
      orte: ["Zürich", "diverse", "Online"],
      sprache: ["Deutsch", "Englisch", "Französisch"],
      zulassungFh: "dossier",
      zulassung: "Nachweis von Projektleitungserfahrung (für Level C mehrere Jahre in den letzten Jahren). Kein Hochschulabschluss nötig.",
      start: "laufend",
      inhalt: "Internationaler Standard für Projektmanagement: Methoden, Führung, Kontext; Prüfung, Bericht und Interview.",
      relevanz: "Branchenunabhängiger Nachweis deiner Projektleitungskompetenz. Er wird besonders bei grösseren Bauherren und in Ausschreibungen geschätzt.",
      nutzen: "Nachweis in Bewerbungen und Angeboten, Aufstieg zur Projektleitung.",
      passung: 3,
      teilVon: [],
      url: "https://www.vzpm.ch/",
      hinweis: "Zulassungsbedingungen beim VZPM prüfen; IPMA Level D ist der Einstieg ohne Erfahrung."
    },

    // ───────────── Recht ─────────────
    {
      id: "hslu-cas-baurecht",
      titel: "CAS Baurecht",
      abschluss: "CAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Technik & Architektur",
      themen: ["Recht", "Projektleitung"],
      ects: 10,
      dauerMonate: 5,
      dauerText: "ca. 1 Semester",
      kostenChf: 7900,
      kostenText: "CHF 7'900 inkl. Einschreibegebühr",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Tertiärer Abschluss (ETH/Uni/FH/HF) und mind. 2 Jahre Berufserfahrung.",
      start: "jährlich",
      inhalt: "Öffentliches und privates Baurecht: Bewilligungsverfahren, SIA-Normen und Verträge, Werkvertrag, Mängelrechte, Haftung, Vergaberecht.",
      relevanz: "Wer ein eigenes Büro führt, trägt das Haftungsrisiko. Rechtswissen schützt dich und deine Kunden und ist auch Wahlmodul im MAS Baumanagement.",
      nutzen: "Verträge sauber aufsetzen, Haftung reduzieren, Baubewilligungsverfahren souverän führen.",
      passung: 4,
      teilVon: ["hslu-mas-bm"],
      url: "https://www.hslu.ch/de-ch/technik-architektur/weiterbildung/bau/cas-baurecht/",
      hinweis: "Dauer nicht verifiziert."
    },
    {
      id: "zhaw-cas-baurecht",
      titel: "CAS Öffentliches Baurecht",
      abschluss: "CAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Recht", "Städtebau & Raum"],
      ects: 12,
      dauerMonate: 6,
      dauerText: "ca. 1 Semester",
      kostenChf: 7500,
      kostenText: "CHF 7'500",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung, Bau oder Verwaltung.",
      start: "jährlich",
      inhalt: "Raumplanungs- und Baurecht, Zonenordnungen, Bewilligungsverfahren, Rechtsmittel, Umweltrecht und Denkmalschutz.",
      relevanz: "Das CAS ist stark auf Bewilligungen und Planungsrecht fokussiert. Das hilft bei Umbauten, wo Bestandesgarantie und Ausnahmebewilligungen zentral sind.",
      nutzen: "Baueingaben, Verhandlungen mit Behörden, Stellen in Bauverwaltungen.",
      passung: 3,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/weiterbildung/detail/kurs/cas-oeffentliches-baurecht",
      hinweis: "Dauer nicht verifiziert."
    },
    {
      id: "unifr-cas-bvr",
      titel: "CAS Bauvertrags- und Vergaberecht für Planungs- und Baufachleute",
      abschluss: "CAS",
      schule: "Uni Freiburg",
      schuleVoll: "Universität Freiburg, Institut für Schweizerisches und Internationales Baurecht",
      themen: ["Recht", "Projektleitung"],
      ects: 10,
      dauerMonate: 6,
      dauerText: "16 Kurstage",
      kostenChf: 9100,
      kostenText: "CHF 9'100 inkl. Unterlagen und Prüfung",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Fribourg"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Planungs- und Baufachleute mit Hochschulabschluss und Praxis.",
      start: "2026 (periodisch)",
      inhalt: "Werkvertrag, SIA 118, Planerverträge (SIA 102), Nachträge, Mängel, öffentliches Beschaffungswesen (BöB/IVöB) aus Sicht der Praxis.",
      relevanz: "Das Freiburger Baurechtsinstitut ist die Referenz in der Schweiz. Vergaberecht ist zentral, wenn du dich als eigenes Büro um öffentliche Aufträge bewerben willst.",
      nutzen: "Angebote bei öffentlichen Ausschreibungen, Nachtragsmanagement, Vertragsverhandlungen.",
      passung: 3,
      teilVon: [],
      url: "https://www.unifr.ch/ius/baurecht/de/weiterbildung/",
      hinweis: "Dauer bitte prüfen."
    },
    {
      id: "fhnw-cas-bauorg",
      titel: "CAS Bauorganisation",
      abschluss: "CAS",
      schule: "FHNW",
      schuleVoll: "FHNW, Hochschule für Architektur, Bau und Geomatik",
      themen: ["Projektleitung"],
      ects: 10,
      dauerMonate: 4,
      dauerText: "ca. 4 Monate",
      kostenChf: 6400,
      kostenText: "CHF 6'400",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Muttenz"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss in Architektur oder Ingenieurwesen und mind. 2 Jahre Berufserfahrung.",
      start: "jährlich",
      inhalt: "Organisation von Bauprojekten und Baustellen: Abläufe, Bauleitung, Termine, Kosten, Qualität und Sicherheit.",
      relevanz: "Ein solider Einstieg in die Bauleitung, der direkt in der Ausführung hilft.",
      nutzen: "Bauleitung, Ausführungsplanung, Kostenkontrolle.",
      passung: 3,
      teilVon: [],
      url: "https://www.fhnw.ch/de/weiterbildung/architektur-bau-geomatik/bauleitung/cas-bauorganisation",
      hinweis: "Ort und Dauer bitte prüfen."
    },
    {
      id: "bfh-brandschutz",
      titel: "Lehrgang Brandschutz für Architekt:innen (Brandschutzfachperson VKF)",
      abschluss: "Lehrgang",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule, Kompetenzzentrum Brandschutz",
      themen: ["Recht", "Projektleitung"],
      ects: null,
      dauerMonate: 6,
      dauerText: "140 Lektionen in 8 Blöcken à 2–3 Tagen (Do–Sa), ca. 200 h Selbststudium",
      kostenChf: 6900,
      kostenText: "CHF 6'900; Bundesbeiträge bei Ablegen der eidg. Prüfung",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Biel"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Architekt:innen mit Berufspraxis; Prüfung als Brandschutzfachfrau/-mann VKF.",
      start: "periodisch",
      inhalt: "VKF-Brandschutzvorschriften, Brandschutzkonzepte, Fluchtwege, Baustoffe, Brandabschnitte, QS-Stufen.",
      relevanz: "Bei Umbauten ist Brandschutz oft der Knackpunkt. Mit dem VKF-Ausweis darfst du Brandschutz-QS bis Stufe 2 selbst verantworten. Das ist ein echter Wettbewerbsvorteil für ein kleines Büro.",
      nutzen: "Brandschutzkonzepte selbst erstellen, Umbauten bewilligungsfähig machen, Zusatzleistung für Kunden.",
      passung: 4,
      teilVon: [],
      url: "https://www.bfh.ch/de/weiterbildung/cas/brandschutz-architektinnen-architekten/",
      hinweis: "Unterrichtsort und Rhythmus prüfen. Alternativen: AFC-Akademie, SVTI."
    },
    {
      id: "reg-a",
      titel: "Registereintrag REG A Architekt:in",
      abschluss: "Register",
      schule: "Stiftung REG",
      schuleVoll: "Schweizerische Stiftung für die Register der Fachleute in den Bereichen Ingenieurwesen, Architektur und Umwelt",
      themen: ["Unternehmertum", "Entwurf & Theorie"],
      ects: null,
      dauerMonate: 12,
      dauerText: "Dossier und Prüfungsverfahren, Dauer individuell",
      kostenChf: null,
      kostenText: "Prüfungsgebühren gemäss Gebührenreglement REG, danach CHF 100 pro Jahr",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch", "Französisch", "Italienisch"],
      zulassungFh: "dossier",
      zulassung: "Mit FH-Bachelor erhältst du REG B (3 Jahre Praxis). REG A setzt einen Master voraus oder ein Prüfungsverfahren, das eine gleichwertige Laufbahn bestätigt.",
      start: "jederzeit",
      inhalt: "Nachweis gleichwertiger Kompetenz auf Masterstufe über Projektdossier und Fachgespräch.",
      relevanz: "Für ein eigenes Büro ist REG A ein Qualitätslabel. In einigen Kantonen (v.a. Westschweiz) ist ein REG-Eintrag Voraussetzung für Baueingaben, und manche Wettbewerbe verlangen ihn.",
      nutzen: "Berufsausübung in Kantonen mit Registerpflicht, Glaubwürdigkeit gegenüber Kunden, Teilnahme an Wettbewerben.",
      passung: 4,
      teilVon: [],
      url: "https://www.reg.ch/eintrag/registereintrag",
      hinweis: "Kein Ausbildungsgang, sondern Anerkennung. Ein konsekutiver Master (siehe unten) führt ebenfalls zu REG A."
    },

    // ───────────── Immobilien ─────────────
    {
      id: "hslu-mas-immo",
      titel: "MAS Immobilienmanagement",
      abschluss: "MAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Wirtschaft, Institut für Finanzdienstleistungen Zug IFZ",
      themen: ["Immobilien", "Unternehmertum"],
      ects: 60,
      dauerMonate: 22,
      dauerText: "22 Monate; ca. alle 2 Wochen Do, Fr und Sa-Vormittag plus 3 Studienwochen",
      kostenChf: 29800,
      kostenText: "CHF 29'800",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Rotkreuz"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung; andere Profile sur dossier.",
      start: "jährlich im Herbst",
      inhalt: "Drei CAS: Real Estate Investment Management, Real Estate Asset Management und Real Estate Development, plus Master-Arbeit.",
      relevanz: "Hier lernst du die Sprache der Investoren: Rendite, Bewertung, Finanzierung. Für eigene Immobilienprojekte oder den Wechsel zur Entwicklerseite ist das zentral.",
      nutzen: "Projektentwicklung, Asset Management, eigene Immobilienprojekte, Wechsel zu Investoren oder Entwicklern.",
      passung: 4,
      teilVon: [],
      url: "https://www.hslu.ch/de-ch/wirtschaft/weiterbildung/mas/ifz/immobilienmanagement/",
      hinweis: ""
    },
    {
      id: "hslu-cas-red",
      titel: "CAS Real Estate Development",
      abschluss: "CAS",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Wirtschaft, IFZ",
      themen: ["Immobilien", "Städtebau & Raum"],
      ects: 15,
      dauerMonate: 6,
      dauerText: "6 Monate (August bis Januar)",
      kostenChf: 9800,
      kostenText: "CHF 9'800 inkl. Unterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Rotkreuz"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung; sur dossier möglich.",
      start: "19.8.2027 (Anmeldeschluss 1.7.2027; 2026 ausgebucht)",
      inhalt: "Standortanalyse, Nutzungskonzepte, Machbarkeit, Wirtschaftlichkeit und Vermarktung von Immobilienprojekten.",
      relevanz: "Für Architekt:innen ist das der naheliegendste Immobilien-Baustein: Du verbindest Entwurf mit Wirtschaftlichkeit. Er ist einzeln oder als Teil des MAS belegbar.",
      nutzen: "Machbarkeitsstudien mit Renditeberechnung, eigene Entwicklungsprojekte, Arbeit bei Entwicklern.",
      passung: 5,
      teilVon: ["hslu-mas-immo"],
      url: "https://www.hslu.ch/de-ch/wirtschaft/weiterbildung/cas/ifz/real-estate-development/",
      hinweis: ""
    },
    {
      id: "curem-mas",
      titel: "MAS UZH in Real Estate (CUREM)",
      abschluss: "MAS",
      schule: "Uni Zürich",
      schuleVoll: "Universität Zürich, CUREM – Center for Urban & Real Estate Management",
      themen: ["Immobilien", "Städtebau & Raum", "Unternehmertum"],
      ects: 70,
      dauerMonate: 18,
      dauerText: "18 Monate; 5 Blockwochen, ca. 28 Wochenenden (Fr/Sa), 1 Auslandreise",
      kostenChf: 38500,
      kostenText: "CHF 38'500 (ohne Reise- und Verpflegungskosten)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und mehrjährige Berufserfahrung; 80 %-Pensum empfohlen.",
      start: "1.3.2027",
      inhalt: "Immobilienökonomie, Finanzierung, Bewertung, Projektentwicklung, Stadtentwicklung, Recht und Nachhaltigkeit im Immobilienmarkt.",
      relevanz: "Das renommierteste Immobilienprogramm der Schweiz mit sehr starkem Alumni-Netzwerk. Es öffnet Türen zu Investoren, Pensionskassen und Entwicklern.",
      nutzen: "Wechsel in Projektentwicklung oder Investment, eigene Immobilienfirma, Netzwerk.",
      passung: 4,
      teilVon: [],
      url: "https://www.curem.uzh.ch/de/weiterbildungen/masterprogramm.html",
      hinweis: ""
    },
    {
      id: "hwz-mas-rem",
      titel: "MAS Real Estate Management HWZ",
      abschluss: "MAS",
      schule: "HWZ",
      schuleVoll: "HWZ Hochschule für Wirtschaft Zürich",
      themen: ["Immobilien", "Digitalisierung & KI", "Projektleitung"],
      ects: 60,
      dauerMonate: 24,
      dauerText: "4 Semester; 3 CAS à 1 Semester plus Master-Thesis",
      kostenChf: 34800,
      kostenText: "CHF 33'850–35'750 je nach Major (ohne Study Tour)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung; sur dossier möglich.",
      start: "halbjährlich",
      inhalt: "Majors: Portfolio und Asset Management, Owner's Project Management oder Digital & AI.",
      relevanz: "Der Major Owner's Project Management passt zur Projektleitung, Digital & AI zu KI. Damit lässt sich das Programm gut auf deine Ziele zuschneiden.",
      nutzen: "Bauherrenvertretung, Immobilien-Asset-Management, PropTech.",
      passung: 4,
      teilVon: [],
      url: "https://fh-hwz.ch/bildungsangebot/weiterbildung/mas/mas-real-estate-management-hwz-major-owner-s-project-management",
      hinweis: ""
    },
    {
      id: "zhaw-mas-refm",
      titel: "MAS in Real Estate und Facility Management",
      abschluss: "MAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Life Sciences und Facility Management, Institut für Facility Management",
      themen: ["Immobilien", "Nachhaltigkeit & Energie"],
      ects: 60,
      dauerMonate: 36,
      dauerText: "modular, max. 5 Jahre",
      kostenChf: 35000,
      kostenText: "ca. CHF 35'000 (CAS einzeln CHF 6'800–9'500)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Wädenswil"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung; sur dossier möglich.",
      start: "laufend über CAS",
      inhalt: "Lebenszyklus von Immobilien, Betrieb, Facility Management, Portfoliomanagement, nachhaltige Bewirtschaftung.",
      relevanz: "Das Programm deckt die Phase nach der Fertigstellung ab. Das ist nützlich, wenn du Gebäude über den ganzen Lebenszyklus denkst, z.B. für Erneuerungsplanung.",
      nutzen: "Portfolio- und Erneuerungsstrategien, Stellen bei institutionellen Eigentümern.",
      passung: 2,
      teilVon: [],
      url: "https://www.zhaw.ch/de/lsfm/weiterbildung/detail/kurs/mas-in-real-estate-und-facility-management",
      hinweis: ""
    },
    {
      id: "ost-cas-immoentw",
      titel: "CAS Immobilienentwicklung",
      abschluss: "CAS",
      schule: "OST",
      schuleVoll: "OST – Ostschweizer Fachhochschule",
      themen: ["Immobilien", "Städtebau & Raum", "Umbau & Bestand"],
      ects: 15,
      dauerMonate: 5,
      dauerText: "5 Monate, 22 Präsenztage",
      kostenChf: 8350,
      kostenText: "CHF 8'350 inkl. Unterlagen und Zertifikat",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Rapperswil-Jona"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Bau, Planung oder Immobilien.",
      start: "jährlich",
      inhalt: "Projektentwicklung bei Neubauten und Bestandsliegenschaften: Standort- und Marktanalyse, Arealentwicklung, Wirtschaftlichkeit.",
      relevanz: "Das CAS deckt ausdrücklich auch die Entwicklung von Bestandsliegenschaften ab. Es verbindet damit Umbau und Immobilien.",
      nutzen: "Machbarkeitsstudien für Bestand und Neubau, eigene Entwicklungsprojekte.",
      passung: 5,
      teilVon: [],
      url: "https://www.ost.ch/de/weiterbildung/weiterbildungsangebot/raum-und-mobilitaet/immobilienmanagement/cas-immobilienentwicklung",
      hinweis: "Unterrichtsort bitte prüfen."
    },
    {
      id: "bfh-cas-areal",
      titel: "CAS Areal- und Immobilienprojektentwicklung",
      abschluss: "CAS",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule",
      themen: ["Immobilien", "Städtebau & Raum"],
      ects: 15,
      dauerMonate: 6,
      dauerText: "ca. 1 Semester",
      kostenChf: 9190,
      kostenText: "CHF 9'190",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Burgdorf"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung.",
      start: "jährlich",
      inhalt: "Entwicklung von Arealen und Immobilienprojekten: Prozesse, Akteure, Standort, Nutzung, Partizipation und Wirtschaftlichkeit.",
      relevanz: "Das CAS ist an der Schnittstelle von Städtebau und Immobilien angesiedelt und eignet sich für grössere Entwicklungsprojekte.",
      nutzen: "Arealentwicklungen, Testplanungen, Rolle zwischen Planung und Investoren.",
      passung: 4,
      teilVon: [],
      url: "https://www.bfh.ch/de/weiterbildung/cas/areal-immobilienprojektentwicklung/",
      hinweis: "Ort und Dauer bitte prüfen."
    },
    {
      id: "eth-cas-arc-immo",
      titel: "CAS ETH ARC in Immobilienstrategien urban–periurban",
      abschluss: "CAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Departement Architektur – Kompetenzzentrum ARC",
      themen: ["Immobilien", "Städtebau & Raum"],
      ects: 12,
      dauerMonate: 12,
      dauerText: "2 Semester, Freitagnachmittag und Samstagvormittag",
      kostenChf: 14000,
      kostenText: "CHF 14'000 inkl. Unterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Master oder gleichwertiges Diplom und mind. 2 Jahre Berufserfahrung. Mit FH-Bachelor sur dossier nachfragen.",
      start: "jährlich im Herbst",
      inhalt: "Immobilienstrategien mit identitätsstiftendem Ansatz für die Schweizer Baukultur, im urbanen und periurbanen Raum.",
      relevanz: "Das CAS verbindet Baukultur mit Immobilienstrategie. Das ist eher selten und passt zu Architekt:innen, die Werte schaffen und nicht nur verwalten wollen.",
      nutzen: "Strategieberatung für Eigentümer, Entwicklung im Agglomerationsraum.",
      passung: 3,
      teilVon: [],
      url: "https://kompetenz.arch.ethz.ch/kurs/cas-eth-arc-immobilienstrategien/",
      hinweis: "Kosten und ECTS analog zu den übrigen CAS ETH ARC. Bitte prüfen."
    },
    {
      id: "svit-fa-entw",
      titel: "Immobilienentwickler/in mit eidg. Fachausweis",
      abschluss: "Fachausweis",
      schule: "SVIT",
      schuleVoll: "SVIT School (Vorbereitung auf die eidg. Berufsprüfung)",
      themen: ["Immobilien", "Unternehmertum"],
      ects: null,
      dauerMonate: 16,
      dauerText: "ca. 16 Monate, rund 380 Lektionen",
      kostenChf: 13300,
      kostenText: "CHF 13'300 (SVIT-Mitglieder CHF 12'500); 50 % Bundesbeitrag nach der Prüfung",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich", "Lausanne"],
      sprache: ["Deutsch", "Französisch"],
      zulassungFh: "dossier",
      zulassung: "Zulassung zur Berufsprüfung mit Berufserfahrung in Immobilien, Planung oder Bau gemäss Prüfungsordnung.",
      start: "periodisch",
      inhalt: "Immobilienentwicklung von der Idee bis zur Vermarktung: Markt, Recht, Finanzierung, Planung, Projektsteuerung.",
      relevanz: "Das ist eine sehr praxisnahe und günstige Alternative zum MAS (dank Bundesbeitrag). Die Branche schätzt den Abschluss, und er richtet sich ausdrücklich auch an Architekt:innen.",
      nutzen: "Eigene Entwicklungsprojekte, Stellen bei Entwicklern und Generalunternehmern.",
      passung: 4,
      teilVon: [],
      url: "https://www.svit.ch/de/education/fa-immobilienentwicklung",
      hinweis: "Eidg. Berufsprüfung, kein Hochschulabschluss."
    },
    {
      id: "fa-bewerter",
      titel: "Immobilienbewerter/in mit eidg. Fachausweis",
      abschluss: "Fachausweis",
      schule: "diverse",
      schuleVoll: "z.B. SVIT, WISS, IREM, Feusi (Vorbereitung auf die eidg. Berufsprüfung)",
      themen: ["Immobilien"],
      ects: null,
      dauerMonate: 14,
      dauerText: "2–3 Semester, ca. 430 Lektionen",
      kostenChf: 13000,
      kostenText: "Kurs CHF 7'800–13'700 plus Prüfung CHF 2'700; bis 50 % Bundesbeitrag",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich", "Bern", "diverse"],
      sprache: ["Deutsch"],
      zulassungFh: "dossier",
      zulassung: "Abgeschlossene Ausbildung (z.B. Bachelor) und mind. 3 Jahre hauptberufliche Praxis in der Immobilienwirtschaft.",
      start: "periodisch",
      inhalt: "Bewertungsmethoden (DCF, Ertragswert, hedonisch), Baukosten, Recht, Marktanalyse, Gutachten.",
      relevanz: "Bewertung ist eine gefragte Nischenkompetenz. Architekt:innen bringen mit der Baukostenkenntnis bereits viel mit.",
      nutzen: "Schätzungen und Gutachten als Zusatzgeschäft, Ankaufsprüfung eigener Objekte.",
      passung: 2,
      teilVon: [],
      url: "https://www.wiss.ch/de-CH/Angebot/Immobilien/Immobilienbewerter-eidg-FA",
      hinweis: "Die 3 Jahre Praxis in der Immobilienwirtschaft sind für Architekt:innen nicht immer erfüllt."
    },

    // ───────────── Unternehmertum ─────────────
    {
      id: "eth-cas-arc-uf",
      titel: "CAS ETH ARC in Unternehmensführung",
      abschluss: "CAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Departement Architektur – Kompetenzzentrum ARC",
      themen: ["Unternehmertum"],
      ects: 12,
      dauerMonate: 12,
      dauerText: "2 Semester, 10 Module, Fr 13–19 Uhr und Sa 9–13 Uhr",
      kostenChf: 14000,
      kostenText: "CHF 14'000 inkl. Unterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Master oder gleichwertiges Diplom und mind. 2 Jahre Berufserfahrung. Mit FH-Bachelor sur dossier nachfragen.",
      start: "jährlich im Herbst",
      inhalt: "Geschäftsmodelle von Planungsbüros, Strategie, Finanzen, Honorare, Akquisition, Führung, Unternehmensnachfolge.",
      relevanz: "Das einzige Unternehmensführungs-CAS, das ausdrücklich für Planende gemacht ist. Es ist die direkteste Vorbereitung auf ein eigenes Architekturbüro.",
      nutzen: "Gründung oder Übernahme eines Büros, Honorarkalkulation, Positionierung.",
      passung: 5,
      teilVon: [],
      url: "https://kompetenz.arch.ethz.ch/kurs/cas-eth-arc-unternehmensfuehrung/",
      hinweis: "Kosten und ECTS analog zu den übrigen CAS ETH ARC. Bitte prüfen."
    },
    {
      id: "kalaidos-cas-ug",
      titel: "CAS FH in Unternehmensgründung",
      abschluss: "CAS",
      schule: "Kalaidos FH",
      schuleVoll: "Kalaidos Fachhochschule (Fernstudium)",
      themen: ["Unternehmertum"],
      ects: 10,
      dauerMonate: 6,
      dauerText: "1 Semester",
      kostenChf: 5000,
      kostenText: "CHF 5'000",
      zeitmodell: ["Teilzeit"],
      form: "Online",
      orte: ["Online"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation mit Berufserfahrung.",
      start: "halbjährlich",
      inhalt: "Chancen und Risiken des Unternehmertums, Businessplan, Gründung und Nachfolge, Marketing und Sanierung, mit Fokus auf KMU.",
      relevanz: "Günstig, ortsunabhängig und gut neben der Arbeit machbar. Am Schluss steht der Businessplan für dein eigenes Büro.",
      nutzen: "Businessplan, Rechtsform, Finanzierung, Gründung.",
      passung: 4,
      teilVon: [],
      url: "https://www.kalaidos-fh.ch/de-CH/Studiengaenge/CAS-Certificate-of-Advanced-Studies-Unternehmensgruendung-Fernstudium",
      hinweis: ""
    },
    {
      id: "fhnw-cas-kmu",
      titel: "CAS Unternehmensführung KMU",
      abschluss: "CAS",
      schule: "FHNW",
      schuleVoll: "FHNW Hochschule für Wirtschaft",
      themen: ["Unternehmertum"],
      ects: 15,
      dauerMonate: 6,
      dauerText: "6 Monate, 15 Unterrichtstage",
      kostenChf: 7900,
      kostenText: "CHF 7'900 inkl. Unterlagen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Basel", "Olten"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation und Führungs- bzw. Berufserfahrung.",
      start: "halbjährlich",
      inhalt: "Strategie, Finanzen, Marketing, Personal und Organisation in KMU; zwei Pflicht- und zwei Wahlmodule, Abschlussarbeit am eigenen Betrieb.",
      relevanz: "Ein Architekturbüro ist ein KMU. Das CAS gibt dir das betriebswirtschaftliche Fundament, das im Bachelor fehlt.",
      nutzen: "Führung eines eigenen oder übernommenen Büros, Finanzplanung, Personalführung.",
      passung: 4,
      teilVon: [],
      url: "https://www.fhnw.ch/de/weiterbildung/wirtschaft/cas-unternehmensfuehrung",
      hinweis: "Unterrichtsort bitte prüfen."
    },
    {
      id: "bfh-cas-ibd",
      titel: "CAS Innovation & Business Design",
      abschluss: "CAS",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule Wirtschaft",
      themen: ["Unternehmertum", "Digitalisierung & KI"],
      ects: 12,
      dauerMonate: 6,
      dauerText: "20 Studientage",
      kostenChf: 8500,
      kostenText: "CHF 8'500",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Bern"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss oder gleichwertige Qualifikation und Berufserfahrung.",
      start: "periodisch (Anmeldung bis 6 Wochen vor Start)",
      inhalt: "Lean Startup, Design Thinking, Value Proposition Design: Innovationen systematisch planen, umsetzen und messen.",
      relevanz: "Design Thinking liegt Architekt:innen nahe. Das CAS hilft, daraus neue Dienstleistungen oder ein Geschäftsmodell zu entwickeln, z.B. ein PropTech- oder Re-Use-Startup.",
      nutzen: "Neue Geschäftsmodelle, Startup-Gründung, Innovationsprojekte im Büro.",
      passung: 3,
      teilVon: [],
      url: "https://www.bfh.ch/en/continuing-education/cas/innovation-business-design/",
      hinweis: ""
    },
    {
      id: "hsg-cas-unt",
      titel: "Unternehmertum CAS-HSG",
      abschluss: "CAS",
      schule: "HSG",
      schuleVoll: "Universität St. Gallen, Executive School",
      themen: ["Unternehmertum"],
      ects: 10,
      dauerMonate: 8,
      dauerText: "17 Tage in 5 Kompaktmodulen, flexibler Einstieg",
      kostenChf: 16900,
      kostenText: "CHF 16'900",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["St. Gallen"],
      sprache: ["Deutsch"],
      zulassungFh: "dossier",
      zulassung: "Zielgruppe: Unternehmer:innen, Gründer:innen und Geschäftsleitungsmitglieder; Aufnahme nach Dossier.",
      start: "flexibler Einstieg",
      inhalt: "Unternehmerische Strategie, Wachstum, Finanzierung, Führung, Nachfolge; Umsetzungsprojekt am eigenen Vorhaben.",
      relevanz: "Teuer, aber mit starkem Netzwerk. Es lohnt sich eher, wenn das eigene Büro bereits läuft und wachsen soll.",
      nutzen: "Wachstumsstrategie, Führung eines wachsenden Büros, Netzwerk.",
      passung: 3,
      teilVon: [],
      url: "https://es.unisg.ch/de/weiterbildung/unternehmertum-cas-hsg/",
      hinweis: ""
    },
    {
      id: "unibe-cas-el",
      titel: "CAS Entrepreneurial Leadership",
      abschluss: "CAS",
      schule: "Uni Bern",
      schuleVoll: "Universität Bern, Entrepreneurship Center",
      themen: ["Unternehmertum"],
      ects: 15,
      dauerMonate: 8,
      dauerText: "Oktober bis Mai",
      kostenChf: 12900,
      kostenText: "CHF 12'900",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Bern"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung; sur dossier möglich.",
      start: "Oktober 2026",
      inhalt: "Unternehmerisches Denken und Handeln, Innovation, Führung in unsicheren Situationen, Geschäftsmodellentwicklung.",
      relevanz: "Das CAS stärkt die unternehmerische Haltung, egal ob für ein eigenes Büro oder als Intrapreneur:in im bestehenden.",
      nutzen: "Gründung, neue Geschäftsfelder, Führungsrollen.",
      passung: 3,
      teilVon: [],
      url: "https://www.unibe.ch/weiterbildungsangebote/cas_entrepreneurial_leadership/index_ger.html",
      hinweis: ""
    },
    {
      id: "eth-mas-mtec",
      titel: "MAS ETH in Management, Technology, and Economics",
      abschluss: "MAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Departement MTEC",
      themen: ["Unternehmertum", "Projektleitung"],
      ects: 60,
      dauerMonate: 24,
      dauerText: "4 Semester; Reduktion auf 80 % empfohlen",
      kostenChf: 23700,
      kostenText: "CHF 23'700",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Englisch"],
      zulassungFh: "dossier",
      zulassung: "Hochschulabschluss (in der Regel Master oder gleichwertig) und mind. 2 Jahre Berufserfahrung. FH-Bachelor: Aufnahme individuell prüfen lassen.",
      start: "jährlich im September",
      inhalt: "Strategie, Finanzen, Innovation, Operations, Technologie- und Innovationsmanagement für Fachleute mit technischem Hintergrund.",
      relevanz: "Ein technischer Management-Abschluss mit ETH-Label. Er ist deutlich günstiger als ein EMBA und eignet sich für den Schritt in Führung oder Geschäftsleitung.",
      nutzen: "Führungsrollen in Planungs- und Bauunternehmen, eigene Firma, Wechsel in Industrie oder Beratung.",
      passung: 3,
      teilVon: [],
      url: "https://sce.ethz.ch/en/programmes-and-courses/search-current-courses/mas/mas-eth-mtec.html",
      hinweis: "Zulassung mit FH-Bachelor bitte direkt bei der ETH klären."
    },
    {
      id: "hwz-emba",
      titel: "Executive MBA General Management HWZ",
      abschluss: "MAS",
      schule: "HWZ",
      schuleVoll: "HWZ Hochschule für Wirtschaft Zürich",
      themen: ["Unternehmertum"],
      ects: 90,
      dauerMonate: 18,
      dauerText: "3 Semester, ca. 60 Präsenztage; 100 %-Pensum möglich",
      kostenChf: 53400,
      kostenText: "CHF 53'400",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und mehrjährige Führungserfahrung.",
      start: "jährlich",
      inhalt: "General Management: Strategie, Finanzen, Marketing, Leadership, Digitalisierung.",
      relevanz: "Ein breiter Management-Abschluss, aber ohne Bau- oder Immobilienbezug. Er lohnt sich eher bei einem Wechsel in eine Geschäftsleitung als für ein kleines eigenes Büro.",
      nutzen: "Geschäftsleitung, Wechsel in andere Branchen.",
      passung: 2,
      teilVon: [],
      url: "https://fh-hwz.ch/en/further-education/emba/executive-mba-general-management-hwz",
      hinweis: "Abschluss ist ein EMBA (Weiterbildungsmaster). Unterrichtssprache prüfen."
    },

    // ───────────── Städtebau & Raum ─────────────
    {
      id: "zhaw-mas-staedtebau",
      titel: "MAS Städtebau",
      abschluss: "MAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Städtebau & Raum", "Entwurf & Theorie"],
      ects: 60,
      dauerMonate: 30,
      dauerText: "5 Semester; 4 CAS à 12 ECTS plus Thesis",
      kostenChf: 32000,
      kostenText: "CHF 32'000 inkl. 4 CAS und Thesis-Betreuung",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss in Architektur, Landschaftsarchitektur, Raumplanung o.ä. und Berufserfahrung.",
      start: "Einstieg über ein CAS",
      inhalt: "CAS Städtebau, Stadtraum Landschaft, Stadtraum Strasse und weitere; Innenentwicklung und Verdichtung.",
      relevanz: "Innenentwicklung heisst Umbau im grossen Massstab. Der MAS eignet sich, wenn dich Quartiere, Areale und Verdichtung mehr interessieren als das Einzelgebäude.",
      nutzen: "Arealentwicklung, Testplanungen, Wettbewerbe im städtebaulichen Massstab, Stellen bei Gemeinden und Städten.",
      passung: 3,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/weiterbildung/detail/kurs/mas-zhaw-staedtebau",
      hinweis: ""
    },
    {
      id: "zhaw-cas-staedtebau",
      titel: "CAS Städtebau",
      abschluss: "CAS",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Städtebau & Raum"],
      ects: 12,
      dauerMonate: 6,
      dauerText: "6 Monate, 20 Tage plus ca. 200 h Selbststudium",
      kostenChf: 7500,
      kostenText: "CHF 7'500 inkl. Unterlagen und Exkursionen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss in Architektur oder verwandtem Gebiet und Berufserfahrung.",
      start: "jährlich",
      inhalt: "Städtebauliches Entwerfen, Typologien, Dichte, Freiraum, Instrumente der Innenentwicklung.",
      relevanz: "Der Einstieg in den städtebaulichen Massstab, ohne dich gleich auf einen MAS festzulegen.",
      nutzen: "Studien und Wettbewerbe im Quartiermassstab, Gestaltungspläne.",
      passung: 3,
      teilVon: ["zhaw-mas-staedtebau"],
      url: "https://www.zhaw.ch/de/archbau/weiterbildung/detail/kurs/cas-staedtebau",
      hinweis: ""
    },
    {
      id: "ost-mas-raum",
      titel: "MAS Raumentwicklung",
      abschluss: "MAS",
      schule: "OST",
      schuleVoll: "OST – Ostschweizer Fachhochschule",
      themen: ["Städtebau & Raum", "Recht"],
      ects: 60,
      dauerMonate: 30,
      dauerText: "5 Semester, 5 Module",
      kostenChf: 30000,
      kostenText: "CHF 30'000 inkl. Thesis (Teil-CAS je CHF 6'500)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Rapperswil-Jona"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung oder Verwaltung.",
      start: "jährlich",
      inhalt: "Raumplanungssystem Schweiz, Siedlungsentwicklung nach innen, Mobilität, Landschaft, Planungsrecht und Prozesse.",
      relevanz: "Eher ein Wechsel in die Raumplanung. Er lohnt sich, wenn du Rahmenbedingungen mitgestalten statt nur innerhalb davon bauen willst.",
      nutzen: "Ortsplanung, Stellen bei Gemeinden/Kantonen, Planungsbüros.",
      passung: 2,
      teilVon: [],
      url: "https://www.ost.ch/de/weiterbildung/weiterbildungsangebot/raum-und-mobilitaet/bau-und-planung/mas-raumentwicklung",
      hinweis: "Mit REG-Eintrag als Raumplaner:in kombinierbar."
    },
    {
      id: "eth-mas-raum",
      titel: "MAS ETH in Raumentwicklung",
      abschluss: "MAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Netzwerk Stadt und Landschaft (NSL)",
      themen: ["Städtebau & Raum"],
      ects: 63,
      dauerMonate: 24,
      dauerText: "2 Jahre, Präsenz ca. 20 % einer Vollzeitstelle",
      kostenChf: null,
      kostenText: "auf der Programmseite nachsehen",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "dossier",
      zulassung: "Hochschulabschluss in einem raumrelevanten Fach und Berufserfahrung; Details bei der ETH erfragen.",
      start: "alle zwei Jahre",
      inhalt: "Raumentwicklung, Planungsinstrumente, Governance, Landschaft und Infrastruktur, Projektarbeit an realen Fallbeispielen.",
      relevanz: "Das ETH-Pendant zum OST-MAS: etwas akademischer und mit starkem Netzwerk in Verwaltung und Planung.",
      nutzen: "Kantonale und kommunale Planung, strategische Raumentwicklung.",
      passung: 2,
      teilVon: [],
      url: "https://www.nsl.ethz.ch/master-of-advanced-studies-eth-in-raumplanung/",
      hinweis: "Kosten nicht gefunden."
    },
    {
      id: "eth-epfl-mas-utd",
      titel: "MAS ETH EPFL in Urban and Territorial Design",
      abschluss: "MAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich und EPFL (Lausanne)",
      themen: ["Städtebau & Raum", "Entwurf & Theorie"],
      ects: 60,
      dauerMonate: 12,
      dauerText: "1 Jahr Vollzeit (Herbst EPFL, Frühling ETH)",
      kostenChf: 15500,
      kostenText: "CHF 15'500 (2 Stipendien verfügbar)",
      zeitmodell: ["Vollzeit"],
      form: "Präsenz",
      orte: ["Lausanne", "Zürich"],
      sprache: ["Englisch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Master in Architektur oder verwandtem Fach vorausgesetzt.",
      start: "jährlich im September",
      inhalt: "Städtebauliches und territoriales Entwerfen auf grossem Massstab, Forschung durch Entwurf, internationale Fallstudien.",
      relevanz: "Ein Entwurfsjahr auf höchstem Niveau, aber Vollzeit und in der Regel erst nach einem Master zugänglich.",
      nutzen: "Städtebau-Wettbewerbe, Forschung, internationale Büros.",
      passung: 1,
      teilVon: [],
      url: "https://sce.ethz.ch/en/programmes-and-courses/search-current-courses/mas/mas-eth-epfl-utd.html",
      hinweis: ""
    },

    // ───────────── Holzbau ─────────────
    {
      id: "bfh-mas-holz",
      titel: "MAS Holzbau",
      abschluss: "MAS",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule, Architektur, Holz und Bau",
      themen: ["Holzbau", "Nachhaltigkeit & Energie"],
      ects: 60,
      dauerMonate: 36,
      dauerText: "ca. 3 Jahre; 4 CAS à 12 ECTS plus Master-Thesis",
      kostenChf: 31000,
      kostenText: "4 CAS à CHF 6'900 (= CHF 27'600) zzgl. Master-Thesis",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Biel"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss in Architektur, Holz- oder Bauingenieurwesen und Berufserfahrung.",
      start: "Einstieg über ein CAS",
      inhalt: "CAS Bauen mit Holz, Entwerfen und Konstruieren mit Holz, Holztragwerke, Bauphysik im Holzbau; Master-Thesis.",
      relevanz: "Holz ist der zentrale Baustoff für CO₂-armes Bauen und eignet sich besonders für Aufstockungen und Umbauten. Biel ist das Schweizer Holzbau-Kompetenzzentrum.",
      nutzen: "Holzbauprojekte, Aufstockungen, Spezialisierung eines eigenen Büros.",
      passung: 4,
      teilVon: [],
      url: "https://www.bfh.ch/de/weiterbildung/cas/bauen-holz/",
      hinweis: "Gesamtkosten geschätzt (Thesis-Gebühr nicht gefunden)."
    },
    {
      id: "bfh-cas-holz",
      titel: "CAS Bauen mit Holz",
      abschluss: "CAS",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule, Architektur, Holz und Bau (auch EN Bau)",
      themen: ["Holzbau", "Nachhaltigkeit & Energie"],
      ects: 12,
      dauerMonate: 6,
      dauerText: "ca. 1 Semester",
      kostenChf: 6900,
      kostenText: "CHF 6'900",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Biel"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung oder Bau.",
      start: "jährlich",
      inhalt: "Holz als Baustoff, Systeme (Rahmen-, Massiv-, Skelettbau), Brandschutz, Schallschutz, Vorfertigung, Ökobilanz.",
      relevanz: "Der Grundlagenbaustein für Holzbau. Er zählt sowohl für den MAS Holzbau als auch für den MAS EN Bau.",
      nutzen: "Holzbau planen und mit Holzbauern auf Augenhöhe zusammenarbeiten.",
      passung: 4,
      teilVon: ["bfh-mas-holz", "enbau-mas"],
      url: "https://www.bfh.ch/de/weiterbildung/cas/bauen-holz/",
      hinweis: "Dauer bitte prüfen."
    },
    {
      id: "bfh-cas-ekholz",
      titel: "CAS Entwerfen und Konstruieren mit Holz",
      abschluss: "CAS",
      schule: "BFH",
      schuleVoll: "Berner Fachhochschule, Architektur, Holz und Bau",
      themen: ["Holzbau", "Entwurf & Theorie"],
      ects: 12,
      dauerMonate: 6,
      dauerText: "ca. 1 Semester",
      kostenChf: 6900,
      kostenText: "CHF 6'900",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Biel"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Hochschulabschluss und Berufserfahrung in Planung oder Bau.",
      start: "jährlich",
      inhalt: "Holzbaugerechtes Entwerfen, Fügung und Detail, Tragstruktur und Raum, Holzhausbau.",
      relevanz: "Das entwurfsorientierte Holz-CAS. Es passt besser zum Architekturprofil als die ingenieurlastigen Module.",
      nutzen: "Entwurf und Detaillierung von Holzbauten, Wettbewerbe mit Holz.",
      passung: 4,
      teilVon: ["bfh-mas-holz"],
      url: "https://www.bfh.ch/de/weiterbildung/cas/holzhausbau/",
      hinweis: "Dauer bitte prüfen."
    },

    // ───────────── Entwurf & Theorie ─────────────
    {
      id: "eth-mas-gta",
      titel: "MAS ETH in Geschichte und Theorie der Architektur",
      abschluss: "MAS",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Institut gta",
      themen: ["Entwurf & Theorie", "Umbau & Bestand"],
      ects: null,
      dauerMonate: 24,
      dauerText: "2 Jahre Teilzeit (4 Semester), Do und Fr an der ETH",
      kostenChf: null,
      kostenText: "CHF 5'500 für den MAS-Teil, zzgl. vorausgesetztes DAS ETH GTA DTM",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Hochschulabschluss (in der Regel Master); Bewerbung 1.4.–30.6.2027.",
      start: "September 2027",
      inhalt: "Architekturgeschichte und -theorie, Archivarbeit, wissenschaftliches Schreiben, Kritik.",
      relevanz: "Das Programm ist akademisch ausgerichtet. Fundiertes Geschichtswissen hilft beim Bauen im Bestand, aber der direkte Nutzen für Büro und Projektleitung ist gering.",
      nutzen: "Architekturkritik, Lehre, Denkmalpflege, Publizistik.",
      passung: 1,
      teilVon: [],
      url: "https://mas.gta.arch.ethz.ch/ueber/info",
      hinweis: "Kosten und ECTS unvollständig, bitte prüfen."
    },

    // ───────────── Konsekutive Master (führen zu REG A) ─────────────
    {
      id: "zhaw-msc-ibe",
      titel: "MSc Integrierte Bau- und Energiesysteme",
      abschluss: "Master",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Nachhaltigkeit & Energie", "Digitalisierung & KI"],
      ects: 90,
      dauerMonate: 30,
      dauerText: "5 Semester Teilzeit (Mo, Do, Fr), 50 % Erwerbstätigkeit möglich",
      kostenChf: 3600,
      kostenText: "CHF 720 pro Semester (≈ CHF 3'600 total)",
      zeitmodell: ["Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Bachelor in Architektur, Ingenieurwesen oder Naturwissenschaften (180 ECTS), Portfolio, ggf. Aufnahmegespräch. Bewerbung bis 31.5.",
      start: "jährlich im Herbst (KW 38)",
      inhalt: "Integrale Planung von Gebäude und Energiesystem, Simulation, Netto-Null-Strategien, Datenmodelle, interdisziplinäre Projekte.",
      relevanz: "Ein vollwertiger Master zu Studiengebühren statt Weiterbildungspreisen. Er passt sehr gut zu Nachhaltigkeit und Daten, und du kannst daneben 50 % arbeiten.",
      nutzen: "Integrale Planung, Energie- und Nachhaltigkeitskoordination, Master-Titel (Basis für REG A).",
      passung: 5,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/studium/masterstudiengang-integrierte-bau-und-energiesysteme",
      hinweis: "MSc, kein Architektur-Master. Ob er zu REG A Architektur führt, bitte bei REG klären."
    },
    {
      id: "zhaw-ma-arch",
      titel: "Master of Arts ZHAW in Architektur",
      abschluss: "Master",
      schule: "ZHAW",
      schuleVoll: "ZHAW Architektur, Gestaltung und Bauingenieurwesen",
      themen: ["Entwurf & Theorie", "Umbau & Bestand", "Städtebau & Raum"],
      ects: 120,
      dauerMonate: 36,
      dauerText: "4 Semester Vollzeit oder 6 Semester Teilzeit (1. Semester Vollzeit)",
      kostenChf: 4320,
      kostenText: "CHF 720 pro Semester",
      zeitmodell: ["Vollzeit", "Teilzeit"],
      form: "Präsenz",
      orte: ["Winterthur"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Bachelor in Architektur; Bewerbung bis 30.4.",
      start: "Herbst (KW 38) oder Frühling (KW 8)",
      inhalt: "Vertiefung in Entwurf, Konstruktion, Städtebau und Theorie mit Masterthesis.",
      relevanz: "Der klassische nächste Schritt nach dem Bachelor. Er führt zu REG A und erweitert die Wettbewerbsfähigkeit, kostet aber Zeit und Pensum.",
      nutzen: "Master-Titel, REG A, Zugang zu Wettbewerben, Lehre und MAS mit Master-Voraussetzung.",
      passung: 3,
      teilVon: [],
      url: "https://www.zhaw.ch/de/archbau/studium/masterstudiengang-architektur",
      hinweis: "Kosten für Teilzeit (6 Semester) gerechnet."
    },
    {
      id: "jma",
      titel: "Joint Master of Architecture (JMA)",
      abschluss: "Master",
      schule: "BFH / HES-SO",
      schuleVoll: "Berner Fachhochschule und HES-SO (HEIA-FR, HEPIA)",
      themen: ["Entwurf & Theorie", "Umbau & Bestand"],
      ects: 120,
      dauerMonate: 42,
      dauerText: "4 Semester Vollzeit oder 7 Semester Teilzeit",
      kostenChf: 5250,
      kostenText: "CHF 750 (BFH) bzw. CHF 950 (HES-SO) pro Semester",
      zeitmodell: ["Vollzeit", "Teilzeit"],
      form: "Präsenz",
      orte: ["Burgdorf", "Fribourg", "Genf"],
      sprache: ["Deutsch", "Französisch"],
      zulassungFh: "ja",
      zulassung: "Bachelor Architektur einer Schweizer FH. Bewerbung bis 31.5. (Herbst) oder 31.10. (Frühling).",
      start: "Herbst oder Frühling",
      inhalt: "Zweisprachiger Master mit Ateliers an mehreren Standorten, Schwerpunkte u.a. in Bauen im Bestand und Territorium.",
      relevanz: "Zweisprachig, mit Teilzeitoption und sehr günstig. Er eignet sich, wenn du einen Master willst und zugleich das Romandie-Netzwerk aufbauen möchtest.",
      nutzen: "Master-Titel, REG A, zweisprachiges Profil.",
      passung: 3,
      teilVon: [],
      url: "https://www.jointmaster.ch/de/zulassung-2/",
      hinweis: "Kosten für Teilzeit (7 Semester, BFH) gerechnet."
    },
    {
      id: "fhnw-ma-arch",
      titel: "Master in Architektur FHNW",
      abschluss: "Master",
      schule: "FHNW",
      schuleVoll: "FHNW, Hochschule für Architektur, Bau und Geomatik (Kooperation mit HSLU)",
      themen: ["Entwurf & Theorie"],
      ects: 120,
      dauerMonate: 24,
      dauerText: "4 Semester Vollzeit",
      kostenChf: 3440,
      kostenText: "CHF 860 pro Semester plus CHF 200 Anmeldung",
      zeitmodell: ["Vollzeit"],
      form: "Präsenz",
      orte: ["Muttenz"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Bachelor in Architektur, in der Regel mit gutem Prädikat.",
      start: "jährlich im Herbst",
      inhalt: "Entwurfsorientierter Master mit Ateliers, Theorie und Masterthesis.",
      relevanz: "Vollzeit-Master nah an Basel. Er führt zu REG A, ist aber nur mit Unterbruch der Berufstätigkeit machbar.",
      nutzen: "Master-Titel, REG A.",
      passung: 2,
      teilVon: [],
      url: "https://www.fhnw.ch/de/architektur-bau-geomatik/studium/angebot/studiengaenge/master-in-architektur",
      hinweis: "Teilzeitmodell nicht angegeben, bitte prüfen."
    },
    {
      id: "hslu-ma-arch",
      titel: "Master Architektur HSLU",
      abschluss: "Master",
      schule: "HSLU",
      schuleVoll: "Hochschule Luzern – Technik & Architektur",
      themen: ["Entwurf & Theorie", "Umbau & Bestand"],
      ects: 120,
      dauerMonate: 36,
      dauerText: "4 Semester Vollzeit, Teilzeit entsprechend länger",
      kostenChf: null,
      kostenText: "Semestergebühr gemäss HSLU-Gebührenordnung (FH-üblich, unter CHF 1'000 pro Semester)",
      zeitmodell: ["Vollzeit", "Teilzeit"],
      form: "Präsenz",
      orte: ["Horw"],
      sprache: ["Deutsch"],
      zulassungFh: "ja",
      zulassung: "Bachelor in Architektur (180 ECTS) mit gutem Prädikat und Aufnahmegespräch mit Portfolio. Aufnahmegebühr CHF 200.",
      start: "jährlich im Herbst",
      inhalt: "Entwurfs- und forschungsorientierter Master, flexibel in Voll- oder Teilzeit kombinierbar.",
      relevanz: "Die Teilzeit-Variante macht den Master neben dem Beruf möglich. Er ist zugleich der direkte Weg zu REG A.",
      nutzen: "Master-Titel, REG A, vertiefte Entwurfskompetenz.",
      passung: 3,
      teilVon: [],
      url: "https://www.hslu.ch/de-ch/technik-architektur/studium/master/",
      hinweis: "Semestergebühr nicht verifiziert."
    },
    {
      id: "eth-msc-arch",
      titel: "MSc ETH in Architektur",
      abschluss: "Master",
      schule: "ETH Zürich",
      schuleVoll: "ETH Zürich, Departement Architektur",
      themen: ["Entwurf & Theorie"],
      ects: 120,
      dauerMonate: 24,
      dauerText: "4 Semester Vollzeit",
      kostenChf: 2920,
      kostenText: "ca. CHF 730 pro Semester",
      zeitmodell: ["Vollzeit"],
      form: "Präsenz",
      orte: ["Zürich"],
      sprache: ["Deutsch", "Englisch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Mit FH-Bachelor nur nach Aufnahmeverfahren mit Portfolio und allenfalls Zusatzauflagen; sehr selektiv.",
      start: "jährlich im Herbst",
      inhalt: "Entwurf auf höchstem Niveau, Konstruktion, Geschichte/Theorie, Städtebau; Diplomarbeit.",
      relevanz: "Höchstes Renommee, aber Vollzeit und mit hoher Zulassungshürde für FH-Absolvent:innen.",
      nutzen: "Master-Titel, REG A, internationales Netzwerk, Zugang zu Lehre.",
      passung: 2,
      teilVon: [],
      url: "https://ethz.ch/de/studium/master/studiengaenge/architektur-und-bauwissenschaften/architektur.html",
      hinweis: "Gebühren und Zulassungsdetails bitte prüfen."
    },
    {
      id: "usi-master",
      titel: "Master of Science in Architettura (Accademia di architettura)",
      abschluss: "Master",
      schule: "USI",
      schuleVoll: "Università della Svizzera italiana, Accademia di architettura Mendrisio",
      themen: ["Entwurf & Theorie", "Städtebau & Raum"],
      ects: 120,
      dauerMonate: 24,
      dauerText: "4 Semester Vollzeit",
      kostenChf: 8000,
      kostenText: "ca. CHF 2'000 pro Semester mit Wohnsitz in der Schweiz",
      zeitmodell: ["Vollzeit"],
      form: "Präsenz",
      orte: ["Mendrisio"],
      sprache: ["Italienisch"],
      zulassungFh: "eingeschraenkt",
      zulassung: "Bachelor Architektur; FH-Absolvent:innen nach Dossierprüfung, allenfalls mit Auflagen.",
      start: "jährlich im Herbst",
      inhalt: "Entwurfsateliers mit international bekannten Architekt:innen, Geschichte, Landschaft, Territorium.",
      relevanz: "Ein Entwurfsmaster mit starkem Charakter und auf Italienisch. Er ist ein Erlebnis, aber Vollzeit und weit weg vom Ziel Projektleitung.",
      nutzen: "Master-Titel, REG A, Italienisch, internationales Netzwerk.",
      passung: 1,
      teilVon: [],
      url: "https://www.arc.usi.ch/",
      hinweis: "Gebühren und Zulassung für FH-Absolvent:innen bitte prüfen."
    }
  ]
};
